info_url = "https://docs.google.com/spreadsheets/d/1pKiV2vD3ZTvjqg0EYyYa9-3whnVaFhGQoYQCHlk7GRE/edit#gid=1668223231"

selected_books_url = "https://docs.google.com/spreadsheets/d/1lt1VLkm728Lkx9zJV7XLmui6_qSirNOHWnHVIqALL4U/edit#gid=1540274189"

stats_url = "https://docs.google.com/spreadsheets/d/1Oxbmc_OP3GTwPiXhYyoXUVK-pEgancDejCpBFHlF6bc/edit#gid=726264491"

interactions_url = "https://docs.google.com/spreadsheets/d/188-QkQltO5e-dsQHFozPS7PeuKjInO1q-g3aJ-1fmy0/edit#gid=1215915440"

book_tags_url = "https://docs.google.com/spreadsheets/d/1441yNTGqVkC_MoFlVK2d_XNJP97nxjSDo8nBUvC0NA8/edit#gid=1641136196"

book_summary_url = "https://docs.google.com/spreadsheets/d/1NXfBMQ1w9qrknZuKxGQHqPVHcmV1-8LfpDc930iI-Kk/edit#gid=193127644"

book_pic_url = "https://docs.google.com/spreadsheets/d/10f6yOXebLT4tWrevev-UH4TgHfxx9gL9cwmOn3iaJUg/edit#gid=65438505"